# Generated by Django 2.0.2 on 2020-05-13 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_map_key', models.IntegerField(unique=True)),
                ('difficulty', models.IntegerField()),
                ('grid_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GridMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=7)),
                ('letter', models.CharField(max_length=1)),
                ('word_key', models.IntegerField()),
                ('grid_map_key', models.ForeignKey(db_column='grid_map_key', on_delete=django.db.models.deletion.CASCADE, to='cws.CollectionGrid', to_field='grid_map_key')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WordCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_collection', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='word_collections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cws.WordCollection'),
        ),
        migrations.AddField(
            model_name='collectiongrid',
            name='word_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cws.WordCollection'),
        ),
    ]
