# Generated by Django 5.0.1 on 2026-02-02 23:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_collection', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Word Collection name can only be alphanumeric.')])),
            ],
            options={
                'verbose_name': 'Word Collection',
                'verbose_name_plural': 'Word Collections',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('word_collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cws.wordcollection')),
            ],
        ),
    ]
