# flake8: noqa

"""
Django settings for WordSearch project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import environ
import os
from .settings_base import *


env = environ.Env()
environ.Env.read_env()


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
LOGGING_DIR = '/var/www/fyw/logs'

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/fyw/static'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/www/fyw/media'


# SECURITY WARNING: SECRET_KEY_FALLBACKS CANNOT BE EMPTY
# SECRET_KEY_FALLBACKS = [
#     env("SECRET_KEY_FALLBACK"),
# ]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'findyourwords.jjbtools.com',
    'www.findyourwords.jjbtools.com',
    '192.168.0.14',
    '127.0.0.1',
    'localhost',
]


# Application definition

INSTALLED_APPS += [

]

MIDDLEWARE += [

]


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USERNAME'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'OPTIONS': {"sslmode": "require"},
        'CONN_MAX_AGE': 3600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS += [

]

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"

# SECURITY WARNING: Locks communication to HTTPS
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_SSL_REDIRECT = True

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"


LOGGING['handlers']['file'] = {
    'level': 'INFO',
    'class': 'logging.FileHandler',
    'formatter': 'file',
    'filename': '/var/www/fyw/logs/debug.log'
}
