# flake8: noqa

"""
Django settings for WordSearch project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import environ
import os
from .settings_base import *


env = environ.Env()
environ.Env.read_env()


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
LOGGING_DIR = '/var/www/tools/fyw/logs'

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/tools/fyw/static'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/www/tools/fyw/media'


# SECURITY WARNING: SECRET_KEY_FALLBACKS CANNOT BE EMPTY
# SECRET_KEY_FALLBACKS = [
#     env("SECRET_KEY_FALLBACK"),
# ]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'findyourwords.jjbtools.com',
    'www.findyourwords.jjbtools.com',
    'localhost']


# Application definition

INSTALLED_APPS += [

]

MIDDLEWARE += [

]


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USERNAME'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS += [

]


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'console': {
#             'format': '%(name)-12s %(levelname)-8s %(message)s'
#         },
#         'file': {
#             'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
#             'datefmt': '%d/%b/%Y %H:%M:%S'
#         }
#     },
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'console'
#         },
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'formatter': 'file',
#             'filename': './logs/debug.log'
#         }
#     },
#     'loggers': {
#         '': {
#             'level': 'DEBUG',
#             'handlers': ['console', 'file']
#         }
#     }
# }
